# Generated by Django 2.2.2 on 2019-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=128, unique=True)),
                ('spot_lat', models.CharField(max_length=256)),
                ('spot_lon', models.CharField(max_length=256)),
                ('spot_time', models.DateTimeField(auto_now_add=True)),
                ('statement', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'spot',
                'verbose_name_plural': 'spot',
                'ordering': ['-spot_time'],
            },
        ),
    ]
