# Generated by Django 2.2.2 on 2019-06-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='spot_type',
            field=models.CharField(choices=[('food', '餐饮'), ('amuse', '娱乐'), ('shopping', '购物'), ('other', '其他')], default='餐饮', max_length=32),
        ),
    ]
