# Generated by Django 2.2.2 on 2019-07-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_spots_spot_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spots',
            options={'ordering': ['-spot_time'], 'verbose_name': 'SPOT', 'verbose_name_plural': 'SPOT'},
        ),
        migrations.AddField(
            model_name='spots',
            name='spot_username',
            field=models.CharField(default=0, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
