# Generated by Django 2.2.2 on 2019-07-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190701_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='spot_username',
            field=models.CharField(max_length=128),
        ),
    ]
